import Head from "next/head";
import LastPost from "../packages/components/LastPost";
import CTAButton from "../packages/components/CTAButton";
import RenderPostList from "../packages/components/RenderPostList";

export default function Home({ users, posts }) {
  return (
    <div>
      <Head>
        <title>BTIX Career Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <LastPost posts={posts} users={users} />

      <RenderPostList posts={posts} users={users} fromPost={1} untilPost={7} />
    </div>
  );
}
