import Head from "next/head";
import LastPost from "../packages/components/LastPost";
import CTAButton from "../packages/components/CTAButton";
import RenderPostList from "../packages/components/RenderPostList";

export default function Home({ posts, users }) {
  return (
    <div>
      <Head>
        <title>BTIX Career Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <LastPost posts={posts} users={users} />

      <RenderPostList posts={posts} users={users} fromPost={1} untilPost={4} />

      <CTAButton>READ MORE STORIES</CTAButton>
    </div>
  );
}

Home.getInitialProps = async (ctx) => {
  const posts = await fetch("https://jsonplaceholder.typicode.com/posts");
  const jsonPosts = await posts.json();

  const users = await fetch("https://jsonplaceholder.typicode.com/users");
  const jsonUsers = await users.json();

  return { posts: jsonPosts, users: jsonUsers };
};
